# -*- coding: utf-8 -*-
"""webscrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pCfLSqoullYiKS-vlgsFfkG06pTJNwf5
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import dateutil.parser as dparser
from datetime import date
import matplotlib.pyplot as plt
import seaborn

doc="""An Giang
Vũng Tàu
Phan Rang
Quy Nhơn
Bạc Liêu
Biên Hòa
Bình Phước
Bắc Kạn
Bắc Giang
Bắc Ninh
Bến Tre
Bình Dương
Bình Định
Bình Phước
Bình Thuận
Cà Mau
Cao Bằng
Cần Thơ
Đà Nẵng
Đà  Nẵng
Đắk Lắk
Đắk Nông
Điện Biên
Đồng Nai
Đồng Tháp
Gia Lai
Hà Giang
Hà Nam
Hà Nội
Hà Tây
Hà Tĩnh
Hạ Long
Hải Dương
Hải Phòng
Hòa Bình
Hồ Chí Minh
Huế
Hậu Giang
Hưng Yên
Khánh Hòa
Kiên Giang
Kon Tum
Lai Châu
Lào Cai
Lạng Sơn
Lâm Đồng
Long An
Long Xuyên
Phú Qúy
Nam Định
Nha Trang
Nghệ An
Ninh Bình
Ninh Thuận
Nha Trang
Miền Tây
Phú Thọ
Phú Yên
Quảng Bình
Quảng Nam
Quảng Ngãi
Quãng Ngãi
Quảng Ninh
Quảng Trị
Sóc Trăng
Sơn La
Tây Ninh
Thái Bình
Thái Nguyên
Thanh Hóa
Huế
Tiền Giang
Trà Vinh
Tuyên Quang
Vĩnh Long
HCM
Vĩnh Phúc
Yên Bái"""
lst=doc.split('\n')
for x in range(0,len(lst)):
    lst[x]=lst[x].lower()

def location(text):
  text=text.lower()
  for x in lst:
    if str(x) in str(text):
      remain=text.replace(x,'')
      return str(x)
  return False

def xu_ly(ngay):
  from datetime import date 
  today = date.today()
  l=list(str(today).split('-'))
  m=int(l[2])-1-ngay

  l[2]=str(m)
  dat=l[2]+'-'+l[1]+'-'+l[0]
  html=f'https://tygiadola.net/LichSuGiaVang?date={dat}'
  print(html)
  page= requests.get(html).text # this is html text
  soup=BeautifulSoup(page,'lxml')
  data=soup.find('table',class_='table table-condensed table-hover table-bordered')
  data=data.find_all('tr',class_='')
  dct={}
  loc=[]
  p_in=[]
  p_out=[]
  dae=[]
  for x in data:
    y=x.find_all('td')
    if len(y)==1:
      continue
    loca=str(y[0].text).strip().replace('\r\n','')
    l=['DOJI HCM','DOJI HN','PNJ HCM','PNJ Hà Nội','Phú Qúy SJC']
    if loca in l:
      continue
    loca=location(loca)
    if loca ==False:
      continue
    g=y[1].find('span')
    g.replaceWith('')
    h=y[2].find('span')
    h.replaceWith('')
    price_in=float(str(y[1].text).strip().replace(',','').replace('\r\n',''))
    price_out=float(str(y[2].text).strip().replace(',','').replace('\r\n',''))
    loc.append(loca)
    p_in.append(price_in)
    p_out.append(price_out)
    dae.append(dat)
  dct['location']=loc
  dct['price_in']=p_in
  dct['price_out']=p_out
  dct['date']=dae
  dataset=pd.DataFrame(dct)
  print(dataset)
  return dataset

def run(chon_ngay_gan_nhat):
  d=[]
  for x in range(chon_ngay_gan_nhat):
    d.append(xu_ly(x))
  result = pd.concat(d,ignore_index=True)
  result.to_csv('im.csv')
  return result
  

df=xu_ly(1)
seaborn.histplot(df,x='price_in',y='price_out',hue='location')
plt.show()
